appliaction:
  name: Backend API Server

server:
  port: 5000


# # Spring properties
spring:
  # Datasource properties. Using MySQL database
  datasource:
    initialization-mode: always
    password:
    username: root
    #It will always use MySQL:SELECT @@GLOBAL.time_zone;
    url: jdbc:mysql://127.0.0.1:3306/marketplace?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    hibernate:
      ddl-auto: update #Change this to none in production environment
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #Jackson date conversion properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    timezone: UTC

  servlet:
    multipart:
      enabled: true
      location: temp123
      file-size-threshold: 5MB
      max-file-size: 2MB
      max-request-size: 10MB


# Application specific custom properties
app:
  config:
    max_age_secs: 3600
  jwt:
    secret: JWTSuperTokenSecretKeyAndJWTSuperTokenSecretKey
    expiration: 604800000 # 7 days expiration time in milli-seconds
  file:
    storage:
      location: media-storage
      max-size: 2048000 #