export const SET_FETCH_ERROR = "GET_FETCH_ERROR";
export const SET_ADD_ERROR = "GET_ADD_ERROR";
export const SET_UPLOAD_ERROR = "SET_UPLOAD_ERROR";
export const SET_USER_PROFILES = "SET_USER_PROFILES";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const ADD_USER_PROFILE = "ADD_USER_PROFILE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const DELETE_USER_PROFILE = "DELETE_USER_PROFILE";

export const SET_USER_LOGGED = "SET_USER_LOGGED";
export const SET_USER_VENDOR = "SET_USER_VENDOR";
export const SET_USER_TOKEN = "SET_USER_TOKEN";

export const GET_PRODUCTS_BY_KEYWORD = "GET_PRODUCTS_BY_KEYWORD";

export const GET_WISHLIST_LIST = "GET_WISHLIST_LIST";
export const ADD_TO_WISHLISH_LIST = "ADD_TO_WISHLISH_LIST";
export const REMOVE_FROM_WISHLIST_LIST = "REMOVE_FROM_WISHLIST_LIST";
export const CLEAR_WISHLIST_LIST = "CLEAR_WISHLIST_LIST";

export const GET_CART = "GET_CART";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREASE_CART_ITEM_QTY = "INCREASE_CART_ITEM_QTY";
export const DECREASE_CART_ITEM_QTY = "DECREASE_CART_ITEM_QTY";
export const UPDATE_CART = "UPDATE_CART";
export const CLEAR_CART = "CLEAR_CART";

export const GET_COMPARE_LIST = "GET_COMPARE_LIST";
export const ADD_TO_COMPARE_LIST = "ADD_TO_COMPARE_LIST";
export const REMOVE_FROM_COMPARE_LIST = "REMOVE_FROM_COMPARE_LIST";
export const CLEAR_COMPARE_LIST = "CLEAR_COMPARE_LIST";
